version: "3.8"

networks:
  ft_bridge:
    name : ft_bridge
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirments/mariadb
    image: ft_mariadb:inception
    init: true
    networks:
      - ft_bridge
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/tmp/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 20s
  wordpress:
    container_name: wordpress
    build: ./requirments/wordpress
    image: ft_wordpress:inception
    init: true
    networks:
      - ft_bridge
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/tmp/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
  nginx:
    container_name: nginx
    build: ./requirments/nginx
    image: ft_nginx:inception
    init: true
    networks:
      - ft_bridge
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443

volumes:
  db_vol:
    name: db_vol
    driver_opts:
      type: none
      o: bind
      device: /home/dkim2/data/db_vol
  wp_vol:
    name: wp_vol
    driver_opts:
      type: none
      o: bind
      device: /home/dkim2/data/wp_vol
