CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;
CREATE USER IF NOT EXISTS ‘dkim2’@’localhost’ IDENTIFIED BY '$WP_ADMIN_PW';
GRANT ALL PRIVILEGES ON $WP_DB_NAME.* to ‘$WP_ADMIN’@’localhost’ identified by '$WP_ADMIN_PW' WITH GRANT OPTION;
FLUSH PRIVILEGES;
