CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;
CREATE USER IF NOT EXISTS '$DB_ADMIN'@'localhost' IDENTIFIED BY '$DB_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON $WP_DB_NAME.* to '$DB_ADMIN'@'localhost' identified by '$DB_ADMIN_PASSWORD' WITH GRANT OPTION;
FLUSH PRIVILEGES;
