version: "3.8"

volumes:
  db_vol:
    driver: local
  wp_vol:
    driver: local

services:
  mariadb:
    container_name: mariadb
    build: ./requirments/mariadb
    init: true
    volumes:
      - db_vol:/val/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirments/wordpress
    init: true
    volumes: 
      - wp_vol:/val/www/html/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    links:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirments/nginx
    init: true
    volumes:
      - wp_vol:/val/www/html/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
    links:
      - wordpress
    ports:
      - 443:443
